PPST/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('doctor/', include('doctor.urls')),
    path('patient/', include('patient.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor/urls.py
from django.urls import path
from . import views

app_name="doctor"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("manageTestLinks/", views.manageTestLinks, name="manageTestLinks"),
    path("datapage/<str:gottenTable>/", views.datapage, name="datapage")
]

doctor/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse, FileResponse
from django.utils import timezone
from django.urls import reverse
from django.conf import settings
from model.models import *
from django.contrib.auth import authenticate, login as log_in, logout as log_out
from django.contrib.auth.models import User
import numpy
import io
import matplotlib.pyplot
import mpld3
import base64
from .spreadsheet.ss import *
from scipy.stats import norm

matplotlib.use('AGG')

def convert_to_dict(instance):
    return {
        'avgLatency1': instance.avgLatency1,
        'avgLatency2': instance.avgLatency2,
        'avgLatency3': instance.avgLatency3,
        'avgLatency4': instance.avgLatency4,
        'avgLatency5': instance.avgLatency5,
        'avgDuration': instance.avgDuration,
        'avg4SpanScore': instance.avg4SpanScore,
        'avg5SpanScore': instance.avg5SpanScore,
        'avgScoreDigit': instance.avgScoreDigit,
        'avgScoreMixed': instance.avgScoreMixed,
        'avgScore': instance.avgScore,
    }
# Create your views here.

def login(request):
     if (request.method == 'GET'):
        return render(request, "doctor/login.html", {})
     else:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']

            doctor = User.objects.filter(username=username).first()
            


            if request.POST.get("action") == "login":
                doctor = authenticate(username=username,password=password)
                if doctor is not None:
                    log_in(request, doctor)
                    return redirect('/doctor/manageTestLinks/')
                else:
                    return render(request, "doctor/login.html", {"error": "Invalid Credentials"})
            
            elif request.POST.get("action") == "signup":
                if doctor is None:
                    # Add doctor signup logic here
                    user = User.objects.create_user(username=username, password=password)
                    log_in(request, user)
                    return redirect('/doctor/manageTestLinks/')
                else:
                    return render(request, "doctor/login.html", {"error": "Invalid Credentials"})
    


def manageTestLinks(request):
    #list1 = ['one', 'two', 'three', 'four', 'five', 'oisdiwdiu'] # Sample list of links for testing
    #list2 = ['True', 'False', 'True', 'True', 'False', 'Invalid'] # Sample list for the status of the link. True means that the test has been completed, False for incomplete, a third option will exist but will be defined when the database is configured for that third option.
    #'Fal2se' is not a typo, it is for testing the third possible test state of "invalidated" or eqivalent.

    doctorToGet = request.user.username
    #Get the specific doctor's links
    user = User.objects.get(username = doctorToGet)
    linkQuery =  doctorLink.objects.filter(doctor = user.id)

    count = 0
    list1 = []
    list2 = []
    for link in linkQuery:
        #print(link.linkID, count)
        list1.append(link.linkID)
        count += 1
        individualTest = individualTable.objects.get(linkID = link)
        #print(individualTest.get_completed_display())
        if individualTest.get_completed_display() == 'Completed':
            list2.append('True')
        elif individualTest.get_completed_display() == 'Incomplete':
            list2.append('False')
        else:
            list2.append('Invalid')
    
    testsList = zip(list1, list2) #zip the lists together to be sent together

    if request.method == 'GET':
        return render(request, "doctor/manageTestLinks.html", {'list' : testsList, 'usersName' : doctorToGet})
    else:
        #trying to display a dynamic number of buttons on the page and assigning them different values that will be sent for different operations
        if 'delete' in request.POST:
            try:
                print(request.POST.get('delete'))
                print("Delete Triggered")
                linkToDelete = doctorLink.objects.get(linkID=request.POST.get('delete'))
                print(f"{bcolors.BOLD}{bcolors.WARNING}Deleting Object:", linkToDelete, f"{bcolors.ENDC}")
                linkToDelete.delete()
                print(f"{bcolors.BOLD}{bcolors.OKGREEN}Object Deleted Successfully", f"{bcolors.ENDC}")
                doctorToGet = request.user.username
                #Get the specific doctor's links
                user = User.objects.get(username = doctorToGet)
                linkQuery =  doctorLink.objects.filter(doctor = user.id)

                count = 0
                list1 = []
                list2 = []
                for link in linkQuery:
                #print(link.linkID, count)
                    list1.append(link.linkID)
                    count += 1
                    individualTest = individualTable.objects.get(linkID = link)
                #print(individualTest.get_completed_display())
                    if individualTest.get_completed_display() == 'Completed':
                        list2.append('True')
                    elif individualTest.get_completed_display() == 'Incomplete':
                        list2.append('False')
                    else:
                        list2.append('Invalid')
                testsList = zip(list1, list2) #zip the lists together to be sent together
                return render(request, "doctor/manageTestLinks.html", {'list' : testsList, 'usersName' : doctorToGet})
            except:
                print(f"{bcolors.FAIL}{bcolors.BOLD}!!!Failed to delete Object!!!{bcolors.ENDC}")
        elif 'download' in request.POST:
            print(request.POST.get('download'))
            print("Download Triggered")
            generateSpreadsheet(request.POST.get('download'))
            filePath = os.path.join(settings.BASE_DIR, 'temp/'+ request.POST.get('download') + '.xlsx') #Getting the path to the file.
            openedFile = open(filePath, 'rb')
            return FileResponse(openedFile)
            #generateSpreadsheet(request.POST.get('download'))
        elif 'view' in request.POST:
            print(request.POST.get('view'))
            print("View Triggered")
            #gottenTable = individualTable.objects.get(linkID=request.POST.get('view'))
            gottenTable = request.POST.get('view')
            #datapage(request, request.POST.get('view'))
            return redirect('doctor:datapage', gottenTable=gottenTable)
        elif 'generateLink' in request.POST:
            print("Generate Link Triggered")
            age = int(request.POST['age'])
            print(age)
            generatedLinkID = generateLink(age, user)
            
            doctorToGet = request.user.username
            #Get the specific doctor's links
            user = User.objects.get(username = doctorToGet)
            linkQuery =  doctorLink.objects.filter(doctor = user.id)

            count = 0
            list1 = []
            list2 = []
            for link in linkQuery:
                #print(link.linkID, count)
                list1.append(link.linkID)
                count += 1
                individualTest = individualTable.objects.get(linkID = link)
                #print(individualTest.get_completed_display())
                if individualTest.get_completed_display() == 'Completed':
                    list2.append('True')
                elif individualTest.get_completed_display() == 'Incomplete':
                    list2.append('False')
                else:
                    list2.append('Invalid')
    
            testsList = zip(list1, list2) #zip the lists together to be sent together

            return render(request, "doctor/manageTestLinks.html", {'list' : testsList, 'usersName' : doctorToGet, 'newLinkID' : generatedLinkID})
            #return HttpResponse(f"Generated Link: {generatedLinkID}") #respond with the input age for testing
        elif 'Logout' in request.POST:
            log_out(request)
            return HttpResponseRedirect("/doctor/login/")

        #Redirect page so that it will properly refresh 
        return HttpResponseRedirect("/doctor/manageTestLinks/")



def datapage(request, gottenTable):

    link = doctorLink.objects.get(linkID=gottenTable)
    variable = None
    if isinstance(gottenTable, str):
        tableToProcess = individualTable.objects.get(linkID=link)
    if request.method=="GET":
        aggregateTable = getAggregateDataForAgeSummary(tableToProcess.age)
        avg = aggregateTable['avgScore']
        sd = aggregateTable['sdScore']
        graph = generateGraph(avg,sd,tableToProcess,None)

    if request.method=="POST":
        tableToProcess = individualTable.objects.get(linkID=link)
        variable = request.POST.get('update', 'Score')
        avg,sd = getAggregateField(variable,tableToProcess.age)
        graph = generateGraph(avg,sd,tableToProcess,f"avg{variable}")
        return render(request, 'doctor/output.html', {
            'avg': round(avg, 3),
            'sd': round(sd, 3),
            'percentile': round(getFieldPercentile(variable, convert_to_dict(tableToProcess).get(f"avg{variable}"), tableToProcess.age), 1),
            'graph': graph,
        })

    return render(request, 'doctor/datapage.html', {'graph': graph, 'avg': round(avg,3), 'sd': round(sd,3), 'percentile': round(getFieldPercentile("Score", tableToProcess.avgScore, tableToProcess.age),1),
    'gottenTable': gottenTable, 'age': tableToProcess.age, 'lat1': round(tableToProcess.avgLatency1,3), 'lat2': round(tableToProcess.avgLatency2,3), 'lat3': round(tableToProcess.avgLatency3,3),
    'lat4': round(tableToProcess.avgLatency4,3), 'lat5': round(tableToProcess.avgLatency5,3), 'variable': variable,'duration': round(tableToProcess.avgDuration,3), '4span': round(tableToProcess.avg4SpanScore,3), '5span': round(tableToProcess.avg5SpanScore,3),

doctor/templates/doctor/datapage.html
{% load static %}
<html>
<head>
    <script src="https://unpkg.com/htmx.org@2.0.3" integrity="sha384-0895/pl2MU10Hqc6jd4RvrthNlDiE9U1tWmX7WRESftEDRosgxNsQG/Ze9YMRzHq" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Page Summary</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: skyblue;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            flex-direction: column;
        }

        .dropdown {
            display: flex;
            justify-content: center;
            margin-top: 30px;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }

        .summary {
            background-color: #007bff89;
            color: white;
            padding: 20px;
            text-align: center;
            border-radius: 8px;
            margin-bottom: 20px;
        }

        .data-table {
            width: 100%;
            margin-top: 20px;
            border-collapse: collapse;
            font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
            font-size: 16px;
        }

        .data-table th, .data-table td {
            padding: 12px;
            text-align: left;
        }

        .data-table th {
            background-color: #343a40;
            color: white;
        }

        .data-table tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .data-table tr:hover {
            background-color: #e0e0e0;
        }

        #data-form {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            width: 300px;
            background-color: #007bff89;
            padding: 20px;
        }

        #data-form label {
            font-size: 18px;
            margin-bottom: 10px;
            font-weight: bold;
            color: white;
            font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        }

        #data-form select {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            font-size: 16px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #f9f9f9;
            box-sizing: border-box;
            transition: border 0.3s ease;
            text-align: center;
            font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        }

        #data-output {
            font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
            font-size: 20px;
        }

    </style>
</head>
<body>

    <div class="container">
        <div class="summary">
            <h1>Data Summary</h1>
        </div>

        <table class="data-table">
            <thead>
                <tr>
                    <th>Age</th>
                    <th>Latency 1</th>
                    <th>Latency 2</th>
                    <th>Latency 3</th>
                    <th>Latency 4</th>
                    <th>Latency 5</th>
                    <th>Duration</th>
                    <th>4-Span</th>
                    <th>5-Span</th>
                    <th>Digit</th>
                    <th>Mixed</th>
                    <th>Score</th>

                </tr>
            </thead>
            <tbody id="data-body">
                <tr>
                    <td>{{age}}</td>
                    <td>{{lat1}}</td>
                    <td>{{lat2}}</td>
                    <td>{{lat3}}</td>
                    <td>{{lat4}}</td>
                    <td>{{lat5}}</td>
                    <td>{{duration}}</td>
                    <td>{{4span}}</td>
                    <td>{{5span}}</td>
                    <td>{{digit}}</td>
                    <td>{{mixed}}</td>
                    <td>{{score}}</td> 
                </tr>
            </tbody>
        </table>
    </div>

    
<div id="dropdown">
    <form method="post" id="data-form" 
      hx-post="{% url 'doctor:datapage' gottenTable %}" 
      hx-trigger="change" 
      hx-target="#data-output" 
      hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    {% csrf_token %}
    <label for="dropdown">Choose a variable:</label>
    <select name="update" id="drop">
        <option value="Latency1">Average Latency 1</option>
        <option value="Latency2">Average Latency 2</option>
        <option value="Latency3">Average Latency 3</option>
        <option value="Latency4">Average Latency 4</option>
        <option value="Latency5">Average Latency 5</option>
        <option value="Duration">Average Duration</option>
        <option value="4SpanScore">Average 4 Span Score</option>
        <option value="5SpanScore">Average 5 Span Score</option>
        <option value="ScoreDigit">Average Score Digit</option>
        <option value="ScoreMixed">Average Score Mixed</option>
        <option value="Score" selected>Average Score</option>
    </select>
    </form>
</div>
<div id="data-output">
    <p>Average: <span id="avg">{{ avg }}</span></p>
    <p>Standard Deviation: <span id="sd">{{ sd }}</span></p>
    <p>Percentile: <span id="percentile">{{ percentile }}</span></p>
    <div id="graph">
        <img id="graph" src="data:image/png;base64,{{ graph }}" alt="Normal Distribution Plot" />
    </div>
    
</div>

</body>
</html>

doctor/templates/doctor/login.html
<!DOCTYPE html>
<html>

<head>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <title>Login Page</title>
    <style>
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            gap: 50px;
        }

        .header {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: flex-start;
            margin-right: 30px;
            font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
            background-color: #00a6ef;;  
            color: white;             
            padding: 20px 30px;     
            border-radius: 10px;       
            border-left-color: black;
        }

        .login {
            display: flex;
            flex-direction: column;
            align-items: flex-start;
            gap: 10px;
        }

        .login input {
            height: 40px;
            width: 505px;
            margin-bottom: 10px;
            font-size: 18px;
            font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        }

        .login input::placeholder {
            font-size: 18px;
            align-content: center;
            font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        }

        .login button {
            height: 45px;
            width: 250px;
            margin-bottom: 10px;
            margin-right: 10px;
            background-color: #00a6ef;
            font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        }

        body{
            background-color: skyblue;
        }

        #response-message {
            font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
            font-size: 30px;
            color: #a10c0c;
            margin-left: 125px;
        }
    </style>
</head>

<body>

    <div class="container">
        <div class="header">
            <h1 style="font-size:600%;">Stat-Link Login</h1>
        </div>

        <div class="login">
            <form method="POST" id="loginForm" action="{% url 'doctor:login' %}">
                {% csrf_token %}

                <input type="text" placeholder="Username" id="username" name="username" style="font-size:18px;"><br>
                <input type="password" placeholder="Password" id="password" name="password"><br>

                <button name="action" value="login" class="btn btn-primary" style="font-size:200%;">Login</button>
                <button name="action" value="signup" class="btn btn-primary" style="font-size:200%;">Signup</button>
            </form>
            <div id="response-message">

            {% if error %}
                <div class="alert alert-danger mt-3" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            </div>
        </div>
    </div>

</body>
</html>

doctor/templates/doctor/manageTestLinks.html
<html>
    <style type="text/css">
        body { background: skyblue !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
     </style>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://unpkg.com/htmx.org@2.0.3" integrity="sha384-0895/pl2MU10Hqc6jd4RvrthNlDiE9U1tWmX7WRESftEDRosgxNsQG/Ze9YMRzHq" crossorigin="anonymous"></script>
</head>
<div id="generateLink"><br>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    <h2 style="text-indent: 15px;">
        Welcome, {{ usersName }}!
        <div class="float-end"> <div class= "container-fluid"><div class="float-end">
            <form action="{% url 'doctor:manageTestLinks' %}" method="post"> {% csrf_token %}
            <button type="submit" class="btn btn-primary" name="Logout"><i class="bi bi-door-closed-fill"></i>Logout</button>
        </form> </div></div>
    </h2> <br style = "line-height:8px;">
    <hr class="border border border-black border-1 opacity-75">
    <h2 style="text-indent: 15px;">
        Manage PPST Test Links<i class="bi bi-clipboard-pulse"></i>
    </h2>
    <h5 style="text-indent: 15px;">
            <div class= "container-fluid"><div class="float-end">
                <input type="text" id="age" name="age" maxlength="20" hidden></input>
            <button type="button"
                name="generateLink"
                hx-trigger="click[confirmAgeValue()]"
                hx-post="{% url 'doctor:manageTestLinks' %}"
                hx-target="#generateLink"
                hx-include="#age" class="btn btn-outline-success"><i class="bi bi-clipboard-plus"></i> Generate Test Link</button></div></div>
                <br>
                <br>
                <br>
                <div class= "container-fluid"><div class="float-end">
                {% if newLinkID %}
                <button type="button" class="btn btn-secondary" onclick="myFunction('{{ newLinkID }}')"><i class="bi bi-copy"></i> Copy Link</button> Generated Link id: {{ newLinkID }}
                {% endif %}</div></div>
        <script>
            function confirmAgeValue()
            {   
                let input = prompt("Enter the age of the patient:");
                //Force an integer to be given
                if(input == null)
                {
                    return false;
                }
                if(isNaN(input) || input < 0)
                {
                    confirm("Please provide a non-negative number. Only digits 0-9 are accepted.\r\nPlease Try again.");
                    return false;
                }

                document.getElementById("age").value = input;
                let valueToDisplay = +document.getElementById("age").value;
                if(confirm("Are you sure you want to generate a new link with associated age?\r\nAge: " + valueToDisplay)) {
                    return true;
                }
            }
        </script>
    </h5>

    <body>
        <br>
        <hr class="border border-black opacity-75">
        {% for el in list %} <!--try and get this to send back an input value-->
            <form action="{% url 'doctor:manageTestLinks' %}" method="post"> {% csrf_token %}
                <div class="container-fluid" style="font-size: 20px;">Link: {{ el.0 }}
                <input type="text" href="http://www.mywebsite.com/sample" value=http://127.0.0.1:8000/patient/welcome/{{el.0}} id={{el.0}} disabled hidden>
                <button type="button" class="btn btn-secondary" onclick="myFunction('{{ el.0 }}')"><i class="bi bi-copy"></i> Copy Link</button>

                {% if el.1 == 'True' %}
                <span class="badge bg-success"><i class="bi bi-check-square"></i> Complete</span> <div class="float-end">
                <button type="submit" onclick="confirmDeleteAction('{{ el.0 }}')" name="delete" value={{el.0}} class="btn btn-outline-danger"><i class="bi bi-x-lg"></i> Delete</button>
                <button type="submit" name="download" value={{el.0}} class="btn btn-outline-success"><i class="bi bi-cloud-download"></i> Download</button>
                <button type="submit" name="view" value={{el.0}} class="btn btn-outline-primary"><i class="bi bi-eye"></i> View</button> </div>
                {% elif el.1 == 'False' %}
                <span class="badge bg-warning text-dark"><i class="bi bi-pencil"></i> Pending</span> <div class="float-end">
                <button type="submit" onclick="confirmDeleteAction('{{ el.0 }}')" name="delete" value={{el.0}} class="btn btn-outline-danger"><i class="bi bi-x-lg"></i> Delete</button> 
                <button type="button" class="btn btn-outline-secondary" disabled><i class="bi bi-cloud-download"></i> Download</button>
                <button type="button" class="btn btn-outline-secondary" disabled><i class="bi bi-eye"></i> View</button></div>
                {% else %}
                <span class="badge bg-danger"><i class="bi bi-exclamation-octagon"></i> Test Invalidated</span><div class="float-end">
                <button type="submit" onclick="confirmDeleteAction('{{ el.0 }}')" name="delete" value={{el.0}} class="btn btn-outline-danger"><i class="bi bi-x-lg"></i> Delete</button> 
                <button type="button" class="btn btn-outline-secondary" disabled><i class="bi bi-cloud-download"></i> Download</button>
                <button type="button" class="btn btn-outline-secondary" disabled><i class="bi bi-eye"></i> View</button></div>
                {% endif %}
            </form>
                </div>
            <hr class="border border-black opacity-75">
        {% endfor %}
        
        <script>
        function myFunction(inputID) {
          // Get the text field
          //var copyText = document.getElementById(inputID);

            var copyText = document.createElement('input'),
            text = window.location.href;

            document.body.appendChild(copyText);
            copyText.value = window.location.origin + "/patient/welcome/" + inputID;
            //copyText.select();
            //document.execCommand('copy');
            //document.body.removeChild(copyText);
        
          // Select the text field
          copyText.select();
          copyText.setSelectionRange(0, 99999); // For mobile devices
        
          // Copy the text inside the text field
          navigator.clipboard.writeText(copyText.value);
          document.body.removeChild(copyText);
          // Alert the copied text
          alert("Copied Link: " + copyText.value + " \nPlease send this to the patient.");
        }
        function confirmDeleteAction(inputID)
        {
            if(confirm("Are you sure you want to delete the following test ID?: " + inputID)) {
                    return true;
                }
            else
            {
                event.preventDefault();
                return false;
            }
        }
        </script>

    </body>
    <script>
        window.addEventListener('beforeunload', function() {
            localStorage.setItem('scrollPosition', window.scrollY);
        });
    </script>
    <script>
    window.addEventListener('load', function() {
        if (localStorage.getItem('scrollPosition')) {
            window.scrollTo({top: localStorage.getItem('scrollPosition'), left: 0, behavior: 'instant'});
            localStorage.removeItem('scrollPosition');
        }
    });
</script>
</body></div>
</html>

doctor/templates/doctor/output.html
<p>Average: {{ avg }}</p>
<p>Standard Deviation: {{ sd }}</p>
<p>Percentile: {{ percentile }}</p>
<img src="data:image/png;base64,{{ graph }}" alt="Normal Distribution Plot">