PPST/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('doctor/', include('doctor.urls')),
    path('patient/', include('patient.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patient/urls.py
from django.urls import path
from . import views

app_name = "patient"

urlpatterns = [
    path("welcome/<int:value>", views.welcome, name="welcome"),
    path("digitIntro", views.digitIntro, name="digitIntro"),
    path("digitKeyboard", views.digitKeyboard, name="digitKeyboard"),
    path("mixedIntro", views.mixedIntro, name="mixedIntro"),
    path("mixedKeyboard", views.mixedKeyboard, name="mixedKeyboard"),
    path("mixedStimuli", views.mixedStimuli, name="mixedStimuli"),
    path("stimuli", views.stimuli, name="stimuli"),
    path("response", views.response, name="response"),
    path("conclusion", views.conclusion, name="conclusion"),
    path("practiceFinish", views.practiceFinish, name="practiceFinish"),
    path("isQuit", views.isQuit, name="isQuit"),
    path("isInvalid", views.isInvalid, name="isInvalid"),
]

patient/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.http import require_GET, require_POST
from django.utils import timezone
from model.models import *
from model import models
from django.core.cache import cache
import json

#local variables
testResults = [[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]

# function to grab stimuli
def getStimuli():
    stimuliJSON = cache.get('stimuliJSON')
    if not stimuliJSON:
        stimulus_queryset = getOrderedStimuli()
        stimuli = [{'givenString': list(stim.givenString)} for stim in stimulus_queryset]
        stimuliJSON = json.dumps(stimuli)
        cache.set('stimuliJSON', stimuliJSON, timeout=3600)  # Cache for 1 hour

    return stimuliJSON
@require_GET
def stimuli(request):
    stimuliJSON = getStimuli()

    return render(request, "patient/stimuli.html", {"stimuliJSON": stimuliJSON})


# Welcome screen
@require_GET
def welcome(request, value):
    global linkID 
    linkID = int(value)
    link = doctorLink.objects.get(linkID=f"{linkID:05}")
    try:
        print("Attempting to fetch individual record")
        individual = individualTable.objects.get(linkID=link)

        if (individual.completed == individualTable.completedStatus.QUIT):
            print("Test Invalid")
            return render (request, "patient/isInvalid.html",)
        elif (individual.completed == individualTable.completedStatus.COMPLETED):
            print("Test Completed")
            return render(request, "patient/completed.html",)
        else:
            print("Test Valid")
            return render(request, "patient/welcome.html",)
    except individualTable.DoesNotExist:
        print("Record not found with the provided linkID") 
        return render(request, "patient/isInvalid.html",)

@require_GET
def isInvalid(request):
    return render(request, "patient/isInvalid.html",)

@require_GET
def digitIntro(request):
    return render(request, "patient/digitIntro.html",)


@require_GET
def digitKeyboard(request):
    return render(request, "patient/digitKeyboard.html",)


@require_GET
def mixedIntro(request):
    return render(request, "patient/mixedIntro.html",)


@require_GET
def mixedKeyboard(request):
    return render(request, "patient/mixedKeyboard.html",)


@require_GET
def mixedStimuli(request):
    return render(request, "patient/mixedStimuli.html",)




def response(request):
    times = request.POST['times']
    currentSetIndex = request.POST['currentSetIndex']
    currentSetIndex = int(currentSetIndex) - 1
    responses = times.split(" ")
    previous = int(responses[0])
    first = int(responses[0])
    responses.pop(0)
    patientAnswerString = ""
    latencyList = []
    for response in responses:
        values = response.split(':')
        button = values[0]
        patientAnswerString = patientAnswerString + button
        latency = (int(values[1]) - previous)/1000
        latencyList.append(latency)
        previous = int(values[1])
    stimulus = getOrderedStimuli()
    testResults[currentSetIndex].append(stimulus[currentSetIndex])
    testResults[currentSetIndex].append(patientAnswerString)
    testResults[currentSetIndex].append(first)
    testResults[currentSetIndex].append(previous)
    testResults[currentSetIndex].append(latencyList)
    if currentSetIndex == 15:
        link = doctorLink.objects.get(linkID=f"{linkID:05}")
        indTable = models.individualTable.objects.get(linkID=link)
        for i in range(16):
            print(testResults[i])
            indResTable = models.individualResultTable.objects.create(
                indTable = indTable,
                testName=stimulus[i],
                patientAnswerString=str(testResults[i][1]),
                startingDayAndTime=datetime.datetime.fromtimestamp(testResults[i][2] / 1000),
                endingDayAndTime=datetime.datetime.fromtimestamp(testResults[i][3] / 1000)
            )
            if len(testResults[i][4]) <= 4:
                latency_data = {}
                for j in range(len(testResults[i][4])):
                    latency_data[f'latency{j+1}'] = testResults[i][4][j]
                models.latency.objects.create(indResTable=indResTable, **latency_data)
            elif len(testResults[i][4]) >= 5:
                models.latency.objects.create(
                    indResTable=indResTable, latency1=testResults[i][4][0], latency2=testResults[i][4][1], latency3=testResults[i][4][2], latency4=testResults[i][4][3], latency5=testResults[i][4][4])
            indResTable.calculateScore()
            indResTable.calculateDuration()
        indTable.calculateData()

    return render(request, "patient/stimuli.html")

def isQuit(request):
    print("isQuit called")
    print("link id: " + str(f"{linkID:05}"))
    
    if request.method == "POST":
        try:
            print("Attempting to fetch individual record")
            link = doctorLink.objects.get(linkID=f"{linkID:05}")
            individual = individualTable.objects.get(linkID=link)
            individual.completed = individualTable.completedStatus.QUIT
            individual.save()
            print("Status updated to QUIT")
            return JsonResponse({"message": "Status updated to QUIT"})
        except individualTable.DoesNotExist:
            print("Record not found with the provided linkID") 
            return JsonResponse({"message": "Record not found"})
        except Exception as e:
            print(f"An error occurred: {e}")
            return JsonResponse({"message": "An error occurred"})
    else:
        print("Received a non-POST request to isQuit view")
        return JsonResponse({"message": "Invalid request"})

def conclusion(request):
    return render(request, "patient/conclusion.html")


def practiceFinish(request):
    return render(request, "patient/practiceFinish.html")

patient/templates/patient/digitIntro.html
<html>

<head>
    {% load static %}
    <script src="https://unpkg.com/htmx.org@2.0.2"
        integrity="sha384-Y7hw+L/jvKeWIRRkqWYfPcvVxHzVzn5REgzbawhxAuQGwX1XWe70vji+VSeHOThJ"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/0e9972534c.js" crossorigin="anonymous"></script>

    <script>

    </script>
    <title>PPST Test</title>

    <style>
        .column {
            padding: 2vmin;
            background-color: #f9f9f9; 
            border-radius: 1vmin; 
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1); 
            margin: 1vmin;
        }

        body {
            font-size: var(--font-size, 3vmin);
        }

        h1 {
            font-size: 6vmin; 
            margin: 0.5vmin;
            width: 100%;
            position: fixed; 
            top: 0;
            left: 0;
            background-color: white;
            z-index: 1;
            padding: 1rem;
            text-align: center; 
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .font-size-buttons {
            margin-top: 0.5rem; 
            font-size: 3vmin;
            color: #555; 
        }

        .font-size-buttons button {
            font-size: 5vmin; 
            padding: 0.5rem;
            margin: 0.2rem;
            cursor: pointer;
            border-radius: 0.3rem;
            border: 1px solid #ccc;
            background-color: #f0f0f0;
            transition: background-color 0.3s ease;
        }

        .font-size-buttons button:hover {
            background-color: #e0e0e0;
        }

        h2 {
            font-size: inherit;
            margin-top: 20vmin;
        }

        p {
            font-size: inherit;
            margin: 0;
            padding: 0.5%;
        }

        hr {
            width: 100%;
            size: 4;
            color: black;
        }

        .button-container button {
            display: flex;
            justify-content: center;
            padding: 1.5% 0;
            width: 30%;
            font-size: 3vw;
            margin: 0 auto;
            border-radius: 2vmin;
        }

        .button-container a {
            text-decoration: none;
        }

        .button-container button:hover {
            background-color: #d5d5d5;
        }

        button i.fas.fa-volume-up {
            font-size: 2vmin;
            color: #007bff;
            transition: color 0.3s ease;
        }

        button:hover i.fas.fa-volume-up {
            color: #0056b3;
        }
    </style>
</head>

<body onload="applySavedFontSize()">


    <header>
        <h1>
            Digit Simuli Introduction
            <div class="font-size-buttons">
                Adjust font size:
                <button onclick="increaseFontSize()">+</button>
                <button onclick="decreaseFontSize()">−</button>
            </div>
            <hr style="height: 0.5vmin; background-color: black; border: none; width: 100%; margin: 0">
        </h1>
    </header>



    <div class ="column">

        <h2>
            <u>Format</u>
    
            <button onclick="playFormat()"
                style="font-size:3vmin; background:none; border:none; padding:0; cursor:pointer;">
                <i class="fas fa-volume-up"></i>
            </button>
        </h2>
    
        <P>
            A number of digits will appear in front of the screen one at a time. After the digits are displayed, selectable
            boxed digits will appear.
            The goal is to select the digits in ascending order that were displayed one at a time. On a desktop, a digit is
            selected by hovering over with the cursor and left clicking with the mouse.
    
            After completing the stimuli, press the “Submit” button to continue.
        </P>
        <br>
        <P> Example: 4512 </P>
        <br>
        <P> Answer: 1245 </P>
        <br>

    </div>
    



    <audio id="format">
        <source src="/patient/media/audio_digitIntroFormat.mp3" type="audio/mpeg">
        Your browser does not support the audio element.
    </audio>


    <script>
        function playFormat() {
            var audio = document.getElementById('format');
            audio.play();
        }
    </script>

    <script>
        function increaseFontSize() {
            document.body.style.setProperty('--font-size', parseFloat(getComputedStyle(document.body).fontSize) * 1.1 + 'px');
            localStorage.setItem('fontSize', fontSize);
        }

        function decreaseFontSize() {
            document.body.style.setProperty('--font-size', parseFloat(getComputedStyle(document.body).fontSize) / 1.1 + 'px');
            localStorage.setItem('fontSize', fontSize);
        }

        function applySavedFontSize() {
            const savedFontSize = localStorage.getItem('fontSize');
            if (savedFontSize) {
                document.body.style.setProperty('--font-size', savedFontSize);
            }
        }
    </script>

    <div id="quit-trigger" hx-post="{% url 'patient:isQuit' %}" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
        style="display:none;"></div>

    <script>
        let isContinuing = false;
        function setContinuing() {
            isContinuing = true;
        }
        window.addEventListener('beforeunload', function (event) {
            if (!isContinuing) {
                document.getElementById("quit-trigger").click();
            }
        });
    </script>

    <div class="button-container">
        <a href="stimuli" onclick="setContinuing()">
            <button>
                Continue
            </button>
        </a>
    </div>
</body>

</html>

patient/templates/patient/digitKeyboard.html
<html>

<head>
    {% load static %}
    <script src="https://unpkg.com/htmx.org@2.0.2"
        integrity="sha384-Y7hw+L/jvKeWIRRkqWYfPcvVxHzVzn5REgzbawhxAuQGwX1XWe70vji+VSeHOThJ"
        crossorigin="anonymous"></script>

    <title>PPST Test</title>

    <style>
        h1 {
            font-size: 4vmin;
            margin: 0;
            width: 100%;
            position: fixed;
            /* Keeps header at the top */
            top: 0;
            background-color: white;
            z-index: 1;
            /* Ensures the header stays on top */
        }

        hr {
            width: 100%;
            size: 4;
            color: black;
        }

        body {
            margin: 0;
            height: 100%;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        .continue-button {
            display: flex;
            justify-content: center;
            padding: 3% 0;
            width: 100%;
            height: 30%;
        } 
        .continue-button button {
            width: 50%;
            height: 50%;
            font-size: 4vmin;
            margin: 0 auto;
            border-radius: 2vmin;
        } 

        
        .continue-button button:hover {
            background-color: #d5d5d5;
        }

        .btn-group {
            width: 100%;
            height: 25%;
            display: flex;
            gap: 5%;
            padding: 1.5% 0;
            justify-content: center;
            border-radius: 2vmin;
        }

        .btn-group button {
            width: 50%;
            height: 100%;
            font-size: 4vmin;
            border-radius: 2vmin;
        }

        .btn-group button:hover {
            background-color: #d5d5d5;
        }
    </style>


</head>

<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>

    <h1>
        Digit Stimuli
        <hr style="height: 0.5vw; background-color: black; border: none; width: 100%;">
    </h1>
    

    <!-- Three buttons in a group -->
    <div class="btn-group" style="margin-top: 20vmin">
        <button id="button2" >5</button>
        <button id="button3" >3</button>
        <button id="button4" >8</button>
        <button id="button5" >4</button>
    </div>

    <div class="btn-group">
        <button id="button6" >7</button>
        <button id="button7" >2</button>
        <button id="button8" >6</button>
        <button id="button9" >9</button>
    </div>

    <script>


        // Record the click on a response button 
        function record(buttonID) {
            return function () {
                
                const button = document.getElementById(buttonID);
                const originalColor = button.style.backgroundColor;

                button.style.backgroundColor = "#ADD8E6"; 

                setTimeout(() => {
                    button.style.backgroundColor = originalColor || "";
                }, 200);

                id = document.getElementById(buttonID)
                val = document.getElementById("times").value
                val = val + ` ${id.innerText}:${Date.now()}`
                document.getElementById("times").value = val
                console.log(document.getElementById("times").value)
            }
        }

        // Setup record function for response buttons
        addEventListener("DOMContentLoaded", (event) => {
            document.getElementById("times").value = `${Date.now()}`
            document.getElementById("button2").onclick = record("button2")
            document.getElementById("button3").onclick = record("button3")
            document.getElementById("button4").onclick = record("button4")
            document.getElementById("button5").onclick = record("button5")
            document.getElementById("button6").onclick = record("button6")
            document.getElementById("button7").onclick = record("button7")
            document.getElementById("button8").onclick = record("button8")
            document.getElementById("button9").onclick = record("button9")
            document.getElementById("currentSetIndex").value = localStorage.getItem('currentSetIndex')
        });
        
        // grab index
        let currentSetIndex = parseInt(localStorage.getItem('currentSetIndex'), 10);

        // function to update header
        window.onload = function () {
            const header = document.querySelector('h1');
            if (currentSetIndex <= 2) {
                header.childNodes[0].nodeValue = "Digit Stimuli Practice";
            } else {
                header.childNodes[0].nodeValue = "Digit Stimuli Test";
            }
        }

        // Function to check number of stimuli sets were done
        function checkRedirect() {
            if (currentSetIndex == 2) {
                window.location.href = "practiceFinish"; 
            } else if (currentSetIndex <= 7) {
                window.location.href = "stimuli"; 
            } else {
                window.location.href = "mixedIntro"; 
            }
        }

    </script>

    <input id="times" value="" type="hidden" name="times"></input>
    <input id="currentSetIndex" value="" type="hidden" name="currentSetIndex"></input>


    <div id="quit-trigger" 
    hx-post="{% url 'patient:isQuit' %}" 
    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
    style="display:none;"></div>

    <script>
        let isContinuing = false;
        function setContinuing() {
            isContinuing = true;
        }

        document.getElementById("continue").addEventListener("htmx:afterRequest", () => {
        setContinuing();
        });
        
        window.addEventListener('beforeunload', function (event) {
            if (!isContinuing) {
                document.getElementById("quit-trigger").click();
            }
        });
    </script>

    <div class="continue-button">

        <button id="continue" hx-trigger="click" hx-post="{% url 'patient:response' %}" hx-include="#times, #currentSetIndex" onclick="checkRedirect(); setContinuing();">
            Continue
        </button>
    </div>


</body>

</html>

patient/templates/patient/mixedIntro.html
<html>

<head>
    {% load static %}
    <script src="https://unpkg.com/htmx.org@2.0.2"
        integrity="sha384-Y7hw+L/jvKeWIRRkqWYfPcvVxHzVzn5REgzbawhxAuQGwX1XWe70vji+VSeHOThJ"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/0e9972534c.js" crossorigin="anonymous"></script>


    <title>PPST Test</title>

    <style>

        .column {
            padding: 2vmin;
            background-color: #f9f9f9; 
            border-radius: 1vmin; 
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1); 
            margin: 1vmin;
        }
        body {
            font-size: var(--font-size, 3vmin);
        }

        h1 {
            font-size: 6vmin; 
            margin: 0.5vmin;
            width: 100%;
            position: fixed; 
            top: 0;
            left: 0;
            background-color: white;
            z-index: 1;
            padding: 1rem;
            text-align: center; 
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .font-size-buttons {
            margin-top: 0.5rem; 
            font-size: 3vmin;
            color: #555; 
        }

        .font-size-buttons button {
            font-size: 5vmin; 
            padding: 0.5rem;
            margin: 0.2rem;
            cursor: pointer;
            border-radius: 0.3rem;
            border: 1px solid #ccc;
            background-color: #f0f0f0;
            transition: background-color 0.3s ease;
        }

        .font-size-buttons button:hover {
            background-color: #e0e0e0;
        }

        h2 {
            font-size: inherit;
            margin-top: 20vmin;
        }

        p {
            font-size: inherit;
            margin: 0;
            padding: 0.5%;
        }

        hr {
            width: 100%;
            size: 4;
            color: black;
        }

        .button-container button {
            display: flex;
            justify-content: center;
            padding: 1.5% 0;
            width: 40%;
            font-size: 3vw;
            margin: 0 auto;
            border-radius: 2vmin;
        }

        .button-container a {
            text-decoration: none;
        }

        .button-container button:hover {
            background-color: #d5d5d5;
        }

        button i.fas.fa-volume-up {
            font-size: 2vmin;
            color: #007bff;
            transition: color 0.3s ease;
        }

        button:hover i.fas.fa-volume-up {
            color: #0056b3;
        }
    </style>
</head>

<body onload="applySavedFontSize()">

    <header>
        <h1>
            Mixed Stimuli Introduction
            <div class="font-size-buttons">
                Adjust font size:
                <button onclick="increaseFontSize()">+</button>
                <button onclick="decreaseFontSize()">−</button>
            </div>
            <hr style="height: 0.5vmin; background-color: black; border: none; width: 100%; margin: 0">
        </h1>
    </header>


    <div class="column">

        <h2>
            <u>Format</u>
    
            <button onclick="playFormat()"
                style="font-size:3vmin; background:none; border:none; padding:0; cursor:pointer;">
                <i class="fas fa-volume-up"></i>
            </button>
        </h2>
    
        <P>
            A mixed number of digits and letters will appear in front of the screen one at a time.
            After the digits/letters are displayed, selectable boxed digits/letters will appear.
            The goal is to select the digits in ascending order followed by letters in alphabetical order that were
            displayed on at a time.
            On a desktop, a digit/letter is selected by hovering over with the cursor and left clicking with the mouse.
            After completing the stimuli, press the “Submit” button to continue.
        </P>
        <br>
        <P> Example: 4JH2 </P>
        <br>
        <P> Answer: 24HJ </P>
        <br>

    </div>
    

    <audio id="format">
        <source src="/patient/media/audio_mixedIntroFormat.mp3" type="audio/mpeg">
        Your browser does not support the audio element.
    </audio>

    <script>
        function playFormat() {
            var audio = document.getElementById('format');
            audio.play();
        }
    </script>

    <script>
        function increaseFontSize() {
            document.body.style.setProperty('--font-size', parseFloat(getComputedStyle(document.body).fontSize) * 1.1 + 'px');
            localStorage.setItem('fontSize', fontSize);
        }

        function decreaseFontSize() {
            document.body.style.setProperty('--font-size', parseFloat(getComputedStyle(document.body).fontSize) / 1.1 + 'px');
            localStorage.setItem('fontSize', fontSize);
        }

        function applySavedFontSize() {
            const savedFontSize = localStorage.getItem('fontSize');
            if (savedFontSize) {
                document.body.style.setProperty('--font-size', savedFontSize);
            }
        }
    </script>


    <div id="quit-trigger" hx-post="{% url 'patient:isQuit' %}" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
        style="display:none;"></div>

    <script>
        let isContinuing = false;
        function setContinuing() {
            isContinuing = true;
        }
        window.addEventListener('beforeunload', function (event) {
            if (!isContinuing) {
                document.getElementById("quit-trigger").click();
            }
        });
    </script>

    <div class="button-container">
        <a href="stimuli" onclick="setContinuing()">
            <button>
                Continue
            </button>
        </a>
    </div>

</body>

</html>

patient/templates/patient/mixedKeyboard.html
<html>

<head>
    {% load static %}
    <script src="https://unpkg.com/htmx.org@2.0.2"
        integrity="sha384-Y7hw+L/jvKeWIRRkqWYfPcvVxHzVzn5REgzbawhxAuQGwX1XWe70vji+VSeHOThJ"
        crossorigin="anonymous"></script>


    <title>PPST Test</title>

    <style>
        h1 {
            font-size: 4vmin;
            margin: 0;
            width: 100%;
            position: fixed;
            /* Keeps header at the top */
            top: 0;
            background-color: white;
            z-index: 1;
            /* Ensures the header stays on top */
        }

        hr {
            width: 100%;
            size: 4;
            color: black;
        }

        body {
            margin: 0;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        .continue-button {
            display: flex;
            justify-content: center;
            padding: 3% 0;
            width: 100%;
            height: 100%;
        } 
        .continue-button button {
            width: 50%;
            height: 70%;
            font-size: 4vmin;
            margin: 0 auto;
            border-radius: 2vmin;
        } 
        
        .continue-button button:hover {
            background-color: #d5d5d5;
        }

        .btn-group {
            width: 100%;
            height: 100%;
            display: flex;
            gap: 3%;
            padding: 1.5% 0;
            justify-content: center;
        }

        .btn-group button {
            width: 50%;
            height: 100%;
            font-size: 4vmin;
            border-radius: 2vmin;
        }

        .btn-group button:hover {
            background-color: #d5d5d5;
        }
    </style>


</head>

<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>

    <h1>
        Mixed Stimuli
        <hr style="height: 0.5vw; background-color: black; border: none; width: 100%;">

</h1>


<div class="btn-group" style="margin-top: 20vmin">
    <button id="button2" >5</button>
    <button id="button3" >3</button>
    <button id="button4" >8</button>
    <button id="button5" >4</button>
  </div>
  <div class="btn-group">
    <button id="button6" >7</button>
    <button id="button7" >2</button>
    <button id="button8" >6</button>
    <button id="button9" >9</button>
  </div>

  <div class="btn-group">
    <button id="buttonJ" >J</button>
    <button id="buttonR" >R</button>
    <button id="buttonW" >W</button>
    <button id="buttonY" >Y</button>
  </div>
  <div class="btn-group">
    <button id="buttonF" >F</button>
    <button id="buttonS" >S</button>
    <button id="buttonK" >K</button>
    <button id="buttonU" >U</button>
  </div>

  <script>

    // Record the click on a response button 
    function record(buttonID) {
            return function () {
                const button = document.getElementById(buttonID);
                const originalColor = button.style.backgroundColor;

                button.style.backgroundColor = "#ADD8E6"; 

                setTimeout(() => {
                    button.style.backgroundColor = originalColor || "";
                }, 200);

                id = document.getElementById(buttonID)
                val = document.getElementById("times").value
                val = val + ` ${id.innerText}:${Date.now()}`
                document.getElementById("times").value = val
                console.log(document.getElementById("times").value)
            }
        }

        // Setup record function for response buttons
        addEventListener("DOMContentLoaded", (event) => {
            document.getElementById("times").value = `${Date.now()}`
            document.getElementById("button2").onclick = record("button2")
            document.getElementById("button3").onclick = record("button3")
            document.getElementById("button4").onclick = record("button4")
            document.getElementById("button5").onclick = record("button5")
            document.getElementById("button6").onclick = record("button6")
            document.getElementById("button7").onclick = record("button7")
            document.getElementById("button8").onclick = record("button8")
            document.getElementById("button9").onclick = record("button9")

            document.getElementById("buttonJ").onclick = record("buttonJ")
            document.getElementById("buttonR").onclick = record("buttonR")
            document.getElementById("buttonW").onclick = record("buttonW")
            document.getElementById("buttonY").onclick = record("buttonY")
            document.getElementById("buttonF").onclick = record("buttonF")
            document.getElementById("buttonS").onclick = record("buttonS")
            document.getElementById("buttonK").onclick = record("buttonK")
            document.getElementById("buttonU").onclick = record("buttonU")

            document.getElementById("currentSetIndex").value = localStorage.getItem('currentSetIndex')
        });
        
        // grab index
        let currentSetIndex = parseInt(localStorage.getItem('currentSetIndex'), 10);
        
            // function to update header
        window.onload = function () {
            const header = document.querySelector('h1');
            if (currentSetIndex <= 9) {
                header.childNodes[0].nodeValue = "Mixed Stimuli Practice";
            } else {
                header.childNodes[0].nodeValue = "Mixed Stimuli Test";
            }
        }
        function checkRedirect() {

            if (currentSetIndex == 10) {
                window.location.href = "practiceFinish"; 
            } else if (currentSetIndex == 16){
                window.location.href = "conclusion"; 
            } else {
                window.location.href = "stimuli"; 
            }
         }
    </script>

    <input id="times" value="" type="hidden" name="times"></input>
    <input id="currentSetIndex" value="" type="hidden" name="currentSetIndex"></input>

    <div id="quit-trigger" 
    hx-post="{% url 'patient:isQuit' %}" 
    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
    style="display:none;"></div>

    <script>
        let isContinuing = false;
        function setContinuing() {
            isContinuing = true;
        }

        document.getElementById("continue").addEventListener("htmx:afterRequest", () => {
        setContinuing();
        });
        
        window.addEventListener('beforeunload', function (event) {
            if (!isContinuing) {
                document.getElementById("quit-trigger").click();
            }
        });
    </script>

    <div class="continue-button">
            <button id="continue" hx-trigger="click" hx-post="{% url 'patient:response' %}" hx-include="#times, #currentSetIndex" onclick="checkRedirect(); setContinuing();">

                Continue
            </button>
    </div>

</body>

</html>